server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker
  file_sd_configs:
    - files: ["/targets/targets.json"]
      refresh_interval: 5s
  relabel_configs:
    # __meta_docker_container_id -> container_id
    # __meta_docker_container_name -> container_name
    # __meta_docker_container_status -> container_status
    - action: "labelmap"
      regex: "__meta_docker_container_(id|name|status)"
      replacement: "container_${1}"
    # add an artificial "instance" label to each stream,
    # so that we can tell which hosts these logs originate from
    - source_labels: ["__address__"]
      target_label: "instance"
      replacement: "127.0.0.1"
  pipeline_stages:
    - docker: {}
